version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: "test-sf5-nginx"
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - .:/var/www/html:rw
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
  php:
    build:
      context: ./docker/php
      args:
        HOST_UID: ${HOST_UID}
    container_name: "test-sf5-php"
    volumes:
      - .:/var/www/html:rw
