<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service/GoogleProtobuf/Proto/Product.proto
namespace App\Service\GoogleProtobuf\GPBMetadata;

class Product
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            '0ab1010a2a536572766963652f476f6f676c6550726f746f6275662f5072' .
            '6f746f2f50726f647563742e70726f746f12204170702e53657276696365' .
            '2e476f6f676c6550726f746f6275662e4d6f64656c22590a0750726f6475' .
            '6374120a0a026964180120012809120d0a057469746c6518022001280912' .
            '130a0b6465736372697074696f6e180320012809120d0a05707269636518' .
            '0420012802120f0a07656e61626c6564180520012808620670726f746f33'
        ), true);

        static::$is_initialized = true;
    }
}
